### ISSUE TITLE
Is JBOM JDK only?

### ISSUE THREAD

**Issue by col-panic** [eclipse/jbom#23]
I'm running this tool inside a Docker container https://github.com/elexis/elexis-server/blob/master/Dockerfile

`java -jar jbom-1.2.1.jar` outputs

```
com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessInitException: Could not execute [jcmd, -l]. Error=2, No such file or directory
	at com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessInitException.newInstance(ProcessInitException.java:80)
	at com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:1002)
	at com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:970)
	at com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
	at com.contrastsecurity.Jbom.getJavaProcesses(Jbom.java:405)
	at com.contrastsecurity.Jbom.doLocalProcess(Jbom.java:142)
	at com.contrastsecurity.Jbom.run(Jbom.java:117)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.contrastsecurity.Jbom.main(Jbom.java:73)
Caused by: java.io.IOException: Cannot run program "jcmd": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at com.contrastsecurity.shaded.org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:997)
	... 14 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.la
```
I can go for that, it seems that jcmd is JDK only. So if i provid the process directly with
with `java -jar jbom-1.2.1.jar -p 157`  the output is

```
Unable to attach with regular provider:
java.lang.IllegalStateException: No compatible attachment provider is available
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:628)
	at net.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:299)
	at com.contrastsecurity.Jbom.attachWithFallback(Jbom.java:443)
	at com.contrastsecurity.Jbom.attach(Jbom.java:429)
	at com.contrastsecurity.Jbom.doLocalProcess(Jbom.java:164)
	at com.contrastsecurity.Jbom.run(Jbom.java:117)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.contrastsecurity.Jbom.main(Jbom.java:73)
Unable to attach with fallback provider:
```

I can't understand this - is this net.bytebuddy also something JDK specific, and is jbom generally not capable of running with JRE only?

**Comment by col-panic** [comment]
BTW this is Java 21

**Comment by planetlevel** [comment]
Looks like there are two issues here.

First, you need some capabilities that are not in JRE.  This explains the exception. I guess a nicer error message would be helpful.   See here for enabling modules -- https://stackoverflow.com/questions/49767683/what-does-no-compatible-attachment-provider-is-available-mean

Second, to run with Java 21 requires an update to bytebuddy version.  Should be pretty straightforward update. https://github.com/raphw/byte-buddy/issues/1396.  

Want to give this a try and submit a PR?  I'd love the help.

**Comment by planetlevel** [comment]
Glad this helped.  I think if you change CycloneDXModel.save() to use something like:
	BomXmlGenerator bomGenerator = BomGeneratorFactory.createJson(CycloneDxSchema.VERSION_LATEST, this);
	String bomString = bomGenerator.toXmlString();			

You could output XML directly.  Again, if you want to add a command line option for this it would be greatly appreciated.

**Comment by planetlevel** [comment]
Have you tried uploading the json SBOM to DependencyTrack?   I'm almost certain it's supported.  Something like this....

curl -X POST -H "Content-Type: application/json" -H "X-API-Key: YOUR_API_KEY" \
-d @my_sbom.json "https://your-dependencytrack-instance/api/v1/bom/PROJECT_UUID"
